### ISSUE TITLE
Center align words in gloss?

### ISSUE THREAD

**Issue by Unknow0059** [Mijyuoon/obsidian-ling-gloss#8]
**problem:**
The words in the gloss are left-aligned.

I'd like them to be center-aligned.

**Comment by Unknow0059** [comment]
**solution:**

create a custom css file

```css
.ling-gloss-level-a { text-align: center; }
.ling-gloss-level-b { text-align: center; }
.ling-gloss-level-c { text-align: center; }
.ling-gloss-level-x { text-align: center; }
```

save it in in `\.obsidian\snippets`

Enable it in Obsidian `Settings > Appearance`
